# Generated by Django 4.1 on 2023-03-16 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('uuid_pk', models.UUIDField(db_column='pk', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city_code', models.SmallIntegerField(db_column='city_code', null=True)),
                ('start', models.BigIntegerField(db_column='start', null=True)),
                ('finish', models.BigIntegerField(db_column='finish', null=True)),
                ('operator', models.CharField(db_column='operator', max_length=4096, null=True)),
                ('geo', models.CharField(db_column='geo', max_length=4096, null=True)),
            ],
            options={
                'db_table': 'csv',
            },
        ),
    ]
