# Generated by Django 4.1 on 2023-03-30 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator', models.CharField(db_column='operator', db_index=True, max_length=4096, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_pk', models.UUIDField(db_column='region_pk', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city_code', models.SmallIntegerField(db_column='city_code', db_index=True)),
                ('geo', models.CharField(db_column='geo', max_length=4096)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField(db_column='start', null=True)),
                ('finish', models.BigIntegerField(db_column='finish', null=True)),
                ('operator', models.ForeignKey(db_column='operator', on_delete=django.db.models.deletion.CASCADE, to='test_case.operator')),
                ('region_pk', models.ForeignKey(db_column='region_pk', on_delete=django.db.models.deletion.CASCADE, to='test_case.region')),
            ],
            options={
                'db_table': 'phone_number',
                'index_together': {('start', 'finish')},
            },
        ),
    ]
